-- Database Creation:

drop database if exists E_Commerce_Order_Management_System;
create database E_Commerce_Order_Management_System;
use E_Commerce_Order_Management_System;

-- Product Table
CREATE TABLE Product (
    ProductID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Category_id INT,
    Price DECIMAL(10, 2) NOT NULL,
    Stock_Quantity INT NOT NULL,
    Added_Date Date NOT NULL,

    foreign key (Category_id) references Category(Category_id)
);
-- Category Table
CREATE TABLE Category (
    Category_id INT PRIMARY KEY AUTO_INCREMENT,
    Category_name VARCHAR(255) NOT NULL
);
-- Customer Table
CREATE TABLE Customer (
    Customer_id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Phone_Number VARCHAR(20),
    Address VARCHAR(100)
    Registration_Date Date NOT NULL
);
-- Orders Table
CREATE TABLE Orders (
    Order_id INT PRIMARY KEY AUTO_INCREMENT,
    Customer_id INT,
    Order_Date Date NOT NULL,
    Total_Amount DECIMAL(10, 2) NOT NULL,
    Status VARCHAR(50) NOT NULL,
);
-- Order_Items Table
CREATE TABLE Order_Items (
    Order_Item_id INT PRIMARY KEY AUTO_INCREMENT,
    Order_id INT,
    Product_id INT,
    Quantity INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,

    foreign key (Order_id) references Orders(Order_id),
    foreign key (Product_id) references Product(Product_id)
);
-- Payment Table
CREATE TABLE Payment (
    Payment_id INT PRIMARY KEY AUTO_INCREMENT,
    Order_id INT,
    Payment_Date Date NOT NULL,
    Payment_Method VARCHAR(50) NOT NULL,
    Payment_Status VARCHAR(50) NOT NULL,
    foreign key (Order_id) references Orders(Order_id)
);
-- Shipping Table
CREATE TABLE Shipping (
    Shipping_id INT PRIMARY KEY AUTO_INCREMENT,
    Order_id INT,
    Shipping_Date Date NOT NULL,
    Delivery_Date Date,
    Shipping_Status VARCHAR(50) NOT NULL,
    foreign key (Order_id) references Orders(Order_id)
);

-- Sample Data Insertion:

-- Tasks and Functionalities:

-- 1. Implement Crud Operatioins

-- . Insert a new product, customer, order into the database.
insert into products(
    Name, Category_id, Price, Stock_Quantity, Added_Date
) values (
    'Laptop', 500, 50, '2024-01-01'    
);

insert into customer(
    Name, Email, Phone_Number, Address, Registration_Date
) values (
    'John Doe', 'john.doe@example.com', '123-456-7890', '123 Main St', '2024-01-01'
);

insert into orders(
    Customer_id, Order_Date, Total_Amount, Status
) values (
    1, '2024-01-01', 500.00, 'Pending'
);

-- . Update the stock quantity When an order is placed.
update product set Stock_Quantity = Stock_Quantity - 1 where ProductID = 1;

-- . Delete orders that were canceled more then 30 days ago.
delete from orders where Status = 'Canceled' and Order_Date < DATE_SUB(CURDATE(), INTERVAL 30 DAY);


-- 2. Use SQL Clause (Having,Where,Limit)

-- . Find all orders placed in last 6 months.
select * from orders where Order_Date >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH);

-- . get the top 5 higest-priced products
select * from product order by Price desc limit 5;

-- . Find the customer who has placed more then 3 orders.
select Customer_id, count(Order_id) as Order_Count from orders group by Customer_id having Order_Count > 3;

-- 3. Apply SQL Operations (And, Or, Not)

-- . Get all products where status is pending and payment status is Paid.
select * from orders where Status = 'Pending' and Payment_Status = 'Paid';

-- Find all products that are Not out of stock.
select * from product where Stock_Quantity > 0;

-- . retrive customers who registered after 2022 or made purchase > 10000.
select * from customer where Registration_Date > '2022-01-01' or Customer_id in (select Customer_id from orders where Total_Amount > 10000);

-- 4. Sorting and Grouping (order by, group by)

-- . List all products sorted by price in descending order.
select * from product order by Price desc);

-- . Display the number of orders placed by each customer.
select Customer_id, count(Order_id) as Order_Count from orders group by Customer_id;

-- . Display the number of orders places by each customer.
select Customer_id, count(Order_id) as Order_Count from orders group by Customer_id;

-- 5. Use Aggregate Functions (Count, Sum, Avg...)

-- Find the total revenue generated by the  store.
select SUM(Total_Amount) as Total_Revenue from orders;

-- . identify the most purchased product.
select Product_id, SUM(Quantity) as Total_Quantity from order_items group by Product_id order by Total_Quantity desc limit 1;

-- . Calculate the average order value.
select AVG(Total_Amount) as Average_Order_Value from orders;

-- 6. Establish Primary and Foreign Key Relationships

-- . Ensure orders are linked to customers.
ALTER TABLE orders
ADD CONSTRAINT fk_customer
FOREIGN KEY (Customer_id) REFERENCES Customer(Customer_id);

-- . Establish a relationship between payments and orders.
ALTER TABLE payment
ADD CONSTRAINT fk_order_payment
FOREIGN KEY (Order_id) REFERENCES Orders(Order_id);

-- 7. Joins

-- . Retrive a list of products along with their category names using  inner join.
select p.Name, c.Category_name from product p
inner join category c on p.Category_id = c.Category_id;

-- . get all orders with customer details using left join.
select o.Order_id, o.Order_Date, c.Name, c.Email from orders o
left join customer c on o.Customer_id = c.Customer_id;

-- . find orders that haven't been shipped using right join.
select o.Order_id, s.Shipping_Status from orders o
right join shipping s on o.Order_id = s.Order_id
where s.Shipping_Status is null;

-- show customers who have never placed an order using full outer join.
select c.Name, o.Order_id from customer c
full outer join orders o on c.Customer_id = o.Customer_id
where o.Order_id is null;

-- 8. Use Subqueries.

-- . Find orders placed by customers who refistered after 2022.
select * from orders where Customer_id in (select Customer_id from customer where Registration_Date > '2022-01-01');

-- . Identify customers who have spent the most .
select Customer_id, SUM(Total_Amount) as Total_Spent from orders group by Customer_id order by Total_Spent desc limit 1;

-- . Get Products that have never been ordered.
select * from product where ProductID not in (select Product_id from order_items);

-- 9. Date and Time Functions

-- . Extract the month from order_date to count orders per month.
select MONTH(Order_Date) as Order_Month, COUNT(Order_id) as Order_Count from orders group by Order_Month;

-- . Calculate Delhivery time by finding the difference between Shipping_Date and Delivery_Date.
select Order_id, DATEDIFF(Delivery_Date, Shipping_Date) as Delivery_Time from shipping;

-- . Formate order_date as DD-MM-YYYY.
select Order_id, DATE_FORMAT(Order_Date, '%d-%m-%Y') as Formatted_Order_Date from orders;

-- 10. String Functions.

-- . Convert all product names to uppercase.
select Name, UPPER(Name) as Uppercase_Name from product;

-- . Trim Whitespace from customer names.
select Name, TRIM(Name) as Trimmed_Name from customer;

-- . Replace missing email values with 'No Email Provided'.
select Name, IFNULL(Email, 'No Email Provided') as Email from customer;

-- 11. Implement Windows Functions.
